### ISSUE TITLE
Add new features to winkler-titrator

### ISSUE THREAD

**Issue by JessyBarrette** [HakaiInstitute/winkler-titrator#1]
Here's a list of new features suggested by @zoehakai to add to the Winkler-titrator package:
-  [ ] #2 `Stop titration` button that closes out files nicely if there’s an issue. Currently have to just close the whole program  
-  [ ] #4 Ability to not choose a port for a standard pump if you don't have one
- [ ] #6 Better error handling from the meter. If the reader gets garbled in any way (because of serial comm issue) then it crashes the titration. Should be able to ignore the error and try to take the read again.
- [ ] Thermocouple input for the temperature of the thiosulfate
- [ ] Thermocouple input for lab air T
- [ ] Input box for the temperature of KIO3 during standardization - either manual input or automatic recording from a thermocouple. 
- [ ] #3 Flag for whether a titration should be considered a standard, a blank, or a sample 
- [ ] #5  Add option to have com ports and flasks calibration path defined within the configuration file wink.ini

All those points should be associated to a unique issue.
